; Teste bancada — 4 OLED SH1106 via TCA9548A (Arduino Mega)
[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600

lib_deps =
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SH110X@^2.1.10
