; Maquete — ext_porta (pedidos exteriores + porta D22)
[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600

build_flags =
    -D ARDUINO_AVR_MEGA2560
