; Código Final 3.0 — versão completa (OLED + pedidos int/ext)
; ARQUIVO CONGELADO — ver README.md
[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SH110X@^2.1.10

build_flags =
    -D ARDUINO_AVR_MEGA2560
