; Código Final 3.0 — variant maquete (sem OLED, sem pedidos interiores, com porta)
[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600

build_flags =
    -D ARDUINO_AVR_MEGA2560
