; PlatformIO — Elevador real (Arduino Mega + L298N + SH1106)
; Compilar: pio run
; Upload:   pio run -t upload
; Monitor:  pio device monitor

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SH110X@^2.1.10

build_flags =
    -D ARDUINO_AVR_MEGA2560
